services:
  mc:
    # :latest 태그로 docker compose pull 시 최신 이미지를 자동으로 가져옴
    image: itzg/minecraft-server:latest
    container_name: mc-crossplay
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "26.1.2"
      MEMORY: "28G"

    volumes:
      - ./data:/data
      - ./plugins:/_staging/plugins:ro
      - ./server.properties:/data/server.properties
      - ./scripts:/data/scripts

    # 기존 서버 실행 명령(/start)을 가로채서
    # 플러그인 자동 설치 스크립트를 먼저 실행한 뒤 서버를 시작
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "bash /data/scripts/update-plugins.sh && /start"

    restart: unless-stopped
    mem_limit: 30000000000
    memswap_limit: 30000000000
